[package]
name = "borker-js-macros"
version = "0.2.0"
authors = ["Sam Sartor <me@samsartor.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
syn = { version = "0.15", features = ["extra-traits"] }
quote = "0.6"
